# apimatic_calculator_zip
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ApimaticCalculatorZip
  # HTTP Methods Enumeration.
  class HttpMethodEnum < CoreLibrary::HttpMethod
  end
end
