# apimatic_calculator_zip
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ApimaticCalculatorZip
  # SimpleCalculatorController
  class SimpleCalculatorController < BaseController
    # Calculates the expression using the specified operation.
    # @param [OperationTypeEnum] operation Required parameter: The operator to
    # apply on the variables
    # @param [Float] x Required parameter: The LHS value
    # @param [Float] y Required parameter: The RHS value
    # @return [Float] Response from the API call.
    def calculate(operation,
                  x,
                  y)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/{operation}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(operation, key: 'operation')
                                    .should_encode(true))
                   .query_param(new_parameter(x, key: 'x'))
                   .query_param(new_parameter(y, key: 'y')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:deserialize_primitive_types))
                    .deserialize_into(proc do |response| response&.to_f end)
                    .is_primitive_response(true))
        .execute
    end
  end
end
