# apimatic_calculator_zip
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ApimaticCalculatorZip
  # Possible operators are sum, subtract, multiply, divide
  class OperationTypeEnum
    OPERATION_TYPE_ENUM = [
      # TODO: Write general description for SUM
      SUM = 'SUM'.freeze,

      # TODO: Write general description for SUBTRACT
      SUBTRACT = 'SUBTRACT'.freeze,

      # TODO: Write general description for MULTIPLY
      MULTIPLY = 'MULTIPLY'.freeze,

      # TODO: Write general description for DIVIDE
      DIVIDE = 'DIVIDE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OPERATION_TYPE_ENUM.include?(value)
    end
  end
end
